blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(ArticleListView.as_view()), name='article_list'),
    path('article_<int:pk>/view/', cache_page(60)(ArticleDetailView.as_view()), name='article_detail'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('article_<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article_<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomeView, ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView, \
    ClientUpdateView, MailingDeleteView, MailingUpdateView, MailingListView, MailingCreateView, MailingDetailView, \
    MailingLogListView, toggle_status

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('client_list/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client_detail_<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update_<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete_<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('mailing_list_<int:pk>/', cache_page(60)(MailingListView.as_view()), name='mailing_list'),
    path('mailing_detail_<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update_<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete_<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('toggle_status_<int:pk>/', toggle_status, name='toggle_status'),

    path('log_list_<int:pk>/', cache_page(60)(MailingLogListView.as_view()), name='log_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import UserRegisterView, UserUpdateView, UserLoginView, verify, send_verify, \
    toggle_activity, UserDetailView, UserListView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('user_detail_<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user_delete_<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('verify_<str:verify_key>/', verify, name='verify'),
    path('send_verify/', send_verify, name='send_verify'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('user_list/', cache_page(30)(UserListView.as_view()), name='user_list'),

]

mailing/models.py
from datetime import date

from django.conf import settings
from django.db import models

from users.models import NULLABLE


class Client(models.Model):
    email = models.EmailField(verbose_name='email')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    patronic_name = models.CharField(max_length=100, **NULLABLE, verbose_name='отчество')
    comment = models.TextField(verbose_name='комментарий')

    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                                 verbose_name='добавлен пользователем')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUSES = (
        (STATUS_STARTED, 'Активна'),
        (STATUS_CREATED, 'Создана'),
        (STATUS_DONE, 'Неактивна'),
    )

    start_date = models.DateField(verbose_name='дата старта рассылки')
    stop_date = models.DateField(**NULLABLE, verbose_name='дата завершения рассылки')
    time = models.TimeField(verbose_name='время отправки')
    period = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность')
    status = models.CharField(max_length=20, default='created', choices=STATUSES, verbose_name='статус рассылки')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                               verbose_name='автор рассылки')
    client = models.ManyToManyField(Client, verbose_name='клиент')

    subject = models.CharField(max_length=100, verbose_name='тема')
    message = models.TextField(verbose_name='сообщение')

    def __str__(self):
        return f'{self.subject} ({self.author})'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    trying_datetime = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус попытки')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    error_message = models.TextField(**NULLABLE, verbose_name='сообщение ошибки')

    def __str__(self):
        return f'{self.mailing}[{self.client}] - {self.status}'

    class Meta:
        verbose_name = 'лог рассылки'
        verbose_name_plural = 'логи рассылки'

mailing/forms.py
from django import forms
import datetime
from mailing.models import Client, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('added_by',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('author', 'status',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['client'].widget = forms.CheckboxSelectMultiple()
        self.fields['client'].queryset = Client.objects.filter(added_by=user)
        self.fields['time'].help_text = 'Введите время в формате ЧЧ:ММ'
        self.fields['start_date'].help_text = 'Введите дату в формате ДД.ММ.ГГГГ'
        self.fields['stop_date'].help_text = 'Введите дату в формате ДД.ММ.ГГГГ (необязательное поле)'

    def clean_start_date(self):
        cleaned_data = self.cleaned_data['start_date']
        if cleaned_data < datetime.date.today():
            raise forms.ValidationError('Дата старта рассылки не может быть меньше текущей')
        return cleaned_data

    def clean_stop_date(self):
        cleaned_data = self.cleaned_data['stop_date']
        if cleaned_data is not None and cleaned_data < datetime.date.today():
            raise forms.ValidationError('Дата завершения рассылки не может быть меньше текущей')
        return cleaned_data

mailing/views.py
import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, UpdateView

from blog.models import Article
from mailing.forms import ClientForm, MailingForm
from mailing.models import Client, Mailing, MailingLog
from mailing.services import get_cache_mailing
from users.models import User


class HomeView(TemplateView):
    template_name = 'mailing/home.html'
    extra_context = {
        'title': 'Главная'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # 3 случайные статьи
        context_data['articles'] = Article.objects.all().order_by('?')[:3]
        return context_data


class ClientListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Мой список клиентов'
    }

    def test_func(self):
        return self.request.user.is_superuser or not self.request.user.is_staff

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(added_by_id=self.request.user.id)

        return queryset


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Client
    extra_context = {
        'title': 'Просмотр клиента'
    }

    def test_func(self):
        return self.request.user == self.get_object().added_by

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings'] = Mailing.objects.filter(client=self.object)
        return context_data


class ClientCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Добавление клиента'
    }

    def test_func(self):
        return not self.request.user.is_staff or self.request.user.is_superuser

    def form_valid(self, form):
        if form.is_valid():
            new_client = form.save()
            new_client.added_by = self.request.user
            new_client.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Редактирование клиента'
    }

    def test_func(self):
        return self.request.user == self.get_object().added_by


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Удаление клиента'
    }

    def test_func(self):
        return self.request.user == self.get_object().added_by


class MailingListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Рассылки'
    }

    def test_func(self):
        user = self.request.user

        # Просмотр cвоих рассылок определенным пользователем
        if self.kwargs.get('pk') != 0:
            author = User.objects.get(pk=self.kwargs.get('pk'))
            return user == author

        # Просмотр рассылок менеджерами рассылок
        else:
            return (user.is_staff and not user.has_perm('blog.add_article')) or user.is_superuser

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.kwargs.get('pk') != 0:
            queryset = queryset.filter(author=self.request.user.id)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.kwargs.get('pk') == 0:
            context_data['all_mailings'] = True
            context_data['title'] = 'Все рассылки'
        else:
            context_data['title'] = 'Мои рассылки'

        return context_data


class MailingDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Mailing
    extra_context = {
        'title': 'Просмотр рассылки'
    }

    def test_func(self):
        user = self.request.user
        return (user.is_staff and not user.has_perm('blog.add_article')) or user == self.get_object().author or user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'], context_data['logs'] = get_cache_mailing(self.object)

        return context_data


class MailingCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    extra_context = {
        'title': 'Добавление рассылки'
    }
    permission_required = 'mailing.add_mailing'

    def test_func(self):
        return not self.request.user.is_staff or self.request.user.is_superuser

    def get_success_url(self):
        return reverse('mailing:mailing_list', args=[self.request.user.id])

    def get_form_kwargs(self):

        # Отправка пользователя в форму для выборки клиентов пользователя (а не всех клиентов сервиса)
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        if form.is_valid():
            new_mailing = form.save()
            new_mailing.author = self.request.user
            new_mailing.save()

        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    extra_context = {
        'title': 'Редактирование рассылки'
    }

    def test_func(self):
        return self.request.user == self.get_object().author

    def get_form_kwargs(self):
        # Отправка пользователя в форму для выборки клиентов пользователя (а не всех клиентов сервиса)
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('mailing:mailing_list', args=[self.request.user.id])


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')
    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('mailing:mailing_list', args=[self.request.user.id])


class MailingLogListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = MailingLog
    extra_context = {
        'title': 'Логи'
    }

    def test_func(self):
        author = Mailing.objects.get(pk=self.kwargs.get('pk')).author
        return self.request.user == author or self.request.user.is_superuser

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(mailing=self.kwargs.get('pk'))

        return queryset


@login_required
@user_passes_test(lambda u: not u.has_perm('blog.add_article') or u.is_superuser)
def toggle_status(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)

    # Проверка на авторство. Прописано в контроллере, поскольку без понятия как в декораторе это написать
    if request.user != mailing_item.author and not request.user.is_staff:
        raise Http404('Отсутствуют права доступа')

    mailing_start_datetime = datetime.datetime.combine(mailing_item.start_date, mailing_item.time)

    if mailing_item.stop_date is not None and mailing_item.stop_date <= datetime.date.today():
        raise Http404('Невозможно активировать завершенную рассылку. Измените дату завершения')
    elif mailing_item.status in ['started', 'created']:
        mailing_item.status = 'done'
    else:
        if mailing_start_datetime < datetime.datetime.now():
            mailing_item.status = 'started'
        else:
            mailing_item.status = 'created'

    mailing_item.save()

    return redirect(reverse('mailing:mailing_detail', args=[pk]))

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{title}}
                    </h4>
                </div>
                <div class="card-body">
                    <table class="table">
                        <caption>Информация о клиенте</caption>
                        <tr>
                            <td>Электронная почта</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        <tr>
                            <td>ФИО</td>
                            <td>{{ object|full_name|title }}</td>
                        </tr>
                        <tr>
                            <td>Комментарий</td>
                            <td>{{ object.comment }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="button-group text-start mb-3">
                        <a href="{% url 'mailing:client_update' object.pk %}" type="button" class="btn btn-warning">Редактировать</a>
                        <a href="{% url 'mailing:client_delete' object.pk %}" type="button" class="btn btn-danger m-2">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Участвует в рассылках
                    </h4>
                </div>
                <div class="card-body">
                    <ul>
                        {% for mailing in mailings %}
                        <li><a href="{% url 'mailing:mailing_detail' mailing.pk %}">{{ mailing }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<div class="container">
    <a href="{% url 'mailing:client_create' %}" type="button" class="btn btn-success mb-4">Добавить клиента</a>
    <table class="table">
        <caption>Список клиентов</caption>
        <thead>
        <tr>
            <th scope="col">Электронная почта</th>
            <th scope="col">ФИО</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td><a href="{% url 'mailing:client_detail' object.pk %}">{{ object.email }}</a></td>
            <td>{{ object|full_name|title }}</td>
            <td>{{ object.comment }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container">
    <table class="table text-center">
        <caption>Статистика</caption>
        <thead>
        <tr>
            <th scope="col">Количество рассылок всего</th>
            <th scope="col">Количество активных рассылок</th>
            <th scope="col">Количество уникальных клиентов</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{% all_mailings %}</td>
            <td>{% active_mailings %}</td>
            <td>{% unique_clients %}</td>
        </tr>
        </tbody>
    </table>
</div>
<div class="featurette-divider"></div>
<div class="container">
    <div id="ArticleCarousel" class="carousel slide mb-6" data-bs-ride="carousel" data-bs-theme="dark">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#ArticleCarousel" data-bs-slide-to="0" class="active"
                    aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#ArticleCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#ArticleCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            {% for article in articles %}
                {% if forloop.first %}
                <div class="carousel-item active">
                {% else %}
                <div class="carousel-item">
                {% endif %}
                    <div class="container">
                        <div class="carousel-caption">
                            <div class="row">
                                <div class="col-6 text-start">
                                    <h1>{{ article.title }}</h1>
                                    <p class="opacity-75">{{ article.content|truncatechars:50 }}</p>
                                    <hr>
                                    <ul class="list-unstyled mt-3 mb-4 text-start opacity-75">
                                        <li>Дата публикации - {{ article.published_at }}</li>
                                    </ul>
                                    <p><a class="btn btn-lg btn-primary" href="{% url 'blog:article_detail' article.pk %}">Читать</a></p>
                                </div>
                                <div class="col-6 text-end">
                                    <img src="/media/{{article.image}}" class="img-fluid" alt="Card image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#ArticleCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#ArticleCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{ title }}
                    </h4>
                </div>
                <div class="card-body">
                    <table class="table">
                        <caption>Рассылка</caption>
                        <tr>
                            <td>Тема</td>
                            <td>{{ object.subject }}</td>
                        </tr>
                        <tr>
                            <td>Сообщение</td>
                            <td>{{ object.message }}</td>
                        </tr>
                        <tr>
                            <td>Время отправки</td>
                            <td>{{ object.time }}</td>
                        </tr>
                        <tr>
                            <td>Дата начала</td>
                            <td>{{ object.start_date }}</td>
                        </tr>
                        <tr>
                            <td>Дата завершения</td>
                            <td>
                                {% if object.stop_date is None %}
                                Не указана
                                {% else %}
                                {{ object.stop_date }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Периодичность</td>
                            <td>{{ object.get_period_display }}</td>
                        </tr>
                        <tr>
                            <td>Статус рассылки</td>
                            <td>{{ object.get_status_display }}</td>
                        </tr>
                    </table>
                    <p>{{ toggle_message }}</p>
                </div>
                <div class="card-footer">
                    <div class="button-group text-start mb-3">
                        {% if user == object.author %}
                        <a href="{% url 'mailing:mailing_update' object.pk %}" type="button" class="btn btn-warning">
                            Редактировать
                        </a>
                        <a href="{% url 'mailing:mailing_delete' object.pk %}" type="button" class="btn btn-danger m-2">
                            Удалить
                        </a>
                        {% endif %}
                        <a href="{% url 'mailing:toggle_status' object.pk %}" type="button"
                           class="btn btn-secondary text-right m-2">
                            {% if object.status == 'started' or object.status == 'created' %}
                            Отключить
                            {% else %}
                            Включить
                            {% endif %}
                        </a>
                        <span>{{ toggle_message }}</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Список рассылки
                    </h4>
                </div>
                <div class="card-body">
                    <ul>
                        {% for client in clients %}
                        <li><a href="{% url 'mailing:client_detail' client.pk %}">{{ client }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h4>Логи</h4>
            </div>
            {% if logs|length == 0 %}
                <p class="text-center">Отсутствуют</p>
            {% else %}
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th scope="col">Дата и время</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Клиент</th>
                            <th scope="col">Сообщение об ошибке</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for log in logs %}
                        <tr>
                            <td>{{ log.trying_datetime }}</td>
                            <td>{{ log.get_status_display }}</td>
                            <td>{{ log.client }}</td>
                            <td>{{ log.error_message }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="mb-3">
                    <a href="{% url 'mailing:log_list' object.pk %}" type="button"
                       class="btn bg-secondary-subtle form-control">
                        Просмотр всех логов
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="container">
    {% if not all_mailings %}
    <a href="{% url 'mailing:mailing_create' %}" type="button" class="btn btn-success mb-4">Добавить рассылку</a>
    {% endif %}
    <table class="table">
        <caption>Список рассылок</caption>
        <thead>
        <tr>
            {% if user.is_staff %}
            <th scope="col">Автор рассылки</th>
            {% endif %}
            <th scope="col">Тема</th>
            <th scope="col">Периодичность</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            {% if user.is_staff %}
            <td><a href="{% url 'users:user_detail' object.author.pk %}">{{ object.author }}</a></td>
            {% endif %}
            <td><a href="{% url 'mailing:mailing_detail' object.pk %}">{{ object.subject }}</a></td>
            <td>{{ object.get_period_display }}</td>
            <td>{{ object.get_status_display }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing/templates/mailing/mailinglog_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% if object_list|length == 0 %}
                <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <h4>Отсутствуют"</h4>
                </div>
            {% else %}
                <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <h4>Рассылка "{{object_list.last.mailing }}"</h4>
                </div>
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th scope="col">Дата и время</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Клиент</th>
                            <th scope="col">Сообщение об ошибке</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for log in object_list reversed %}
                        <tr>
                            <td>{{ log.trying_datetime }}</td>
                            <td>{{ log.get_status_display }}</td>
                            <td>{{ log.client }}</td>
                            <td>{{ log.error_message }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}