blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(ArticleListView.as_view()), name='article_list'),
    path('article_<int:pk>/view/', cache_page(60)(ArticleDetailView.as_view()), name='article_detail'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('article_<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article_<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import NULLABLE


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержание')
    image = models.ImageField(upload_to='articles/', verbose_name='превью', **NULLABLE)
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    views_count = models.PositiveIntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ('published_at',)

blog/forms.py
from django import forms

from blog.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('views_count',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from blog.forms import ArticleForm
from blog.models import Article
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy


class ArticleListView(ListView):
    model = Article
    extra_context = {
        'title': 'Блог'
    }


class ArticleDetailView(DetailView):
    model = Article
    extra_context = {
        'title': 'Статья',
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm

    success_url = reverse_lazy('blog:article_list')
    extra_context = {
        'title': 'Создание статьи',
    }
    permission_required = 'blog.add_article'


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm

    extra_context = {
        'title': 'Редактирование статьи',
    }
    permission_required = 'blog.change_article'

    def get_success_url(self):
        return reverse('blog:article_detail', args=[self.kwargs.get('pk'), self.kwargs.get('slug')])


class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:article_list')
    extra_context = {
        'title': 'Удаление статьи',
    }
    permission_required = 'blog.delete_article'

blog/templates/blog/article_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
            <div class="card col m-4">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Подтвердить удаление "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:article_detail' object.pk %}" class="btn btn-warning">
                            Отмена
                        </a>
                    </form>
                </div>
            </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4">
            <img src="/media/{{ object.image }}" alt="#IMAGE#" class="img-fluid">
        </div>
        <div class="col">
            <h3>{{ object.title }}</h3>
            <p>{{ object.content }}</p>
        </div>
    </div>
    <hr>
    <div class="col-4">
        {% if perms.blog.add_article %}
        <p class="btn-group">
            <a class="btn btn-outline-primary" href="{% url 'blog:article_update' object.pk %}"
               role="button">
                Редактировать
            </a>
            <a class="btn btn-outline-danger" href="{% url 'blog:article_delete' object.pk %}"
               role="button">
                Удалить
            </a>
        </p>
        {% endif %}
        <p>
            Дата публикации {{ object.published_at }}
        </p>
        <p>
            Просмотры {{ object.views_count }}
        </p>
    </div>
</div>

{% endblock %}

blog/templates/blog/article_form.html
{% extends 'mailing/base.html' %}

{% block content %}
        <div class="row">
            <div class="col-3"></div>
                <div class="col-md-6">
                    <div class="card-header">
                        <h4>
                            {% if object %}
                                    Редактировать статью
                                {% else %}
                                    Добавить статью
                                {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
        </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="container">
    {% if perms.blog.add_article %}
    <div class="col-12 mb-5">
        <a class="btn btn-success" href="{% url 'blog:article_create' %}">Добавить статью</a>
    </div>
    {% endif %}
    <div class="row">

        {% for object in object_list %}
            <div class="col-md-4">
                <div class="col">
                    <img class="rounded img-fluid" src="/media/{{ object.image }}" alt="Card image">
                </div>
                <h3>{{ object.title }}</h3>
                <p>{{ object.content|truncatechars:200 }}</p>
                <div class="btn-group">
                <p>
                        <a class="btn btn-outline-info" href="{% url 'blog:article_detail' object.pk %}"
                           role="button">
                            Перейти к статье
                        </a>
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}