blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(ArticleListView.as_view()), name='article_list'),
    path('article_<int:pk>/view/', cache_page(60)(ArticleDetailView.as_view()), name='article_detail'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('article_<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article_<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomeView, ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView, \
    ClientUpdateView, MailingDeleteView, MailingUpdateView, MailingListView, MailingCreateView, MailingDetailView, \
    MailingLogListView, toggle_status

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('client_list/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client_detail_<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update_<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete_<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('mailing_list_<int:pk>/', cache_page(60)(MailingListView.as_view()), name='mailing_list'),
    path('mailing_detail_<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update_<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete_<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('toggle_status_<int:pk>/', toggle_status, name='toggle_status'),

    path('log_list_<int:pk>/', cache_page(60)(MailingLogListView.as_view()), name='log_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import UserRegisterView, UserUpdateView, UserLoginView, verify, send_verify, \
    toggle_activity, UserDetailView, UserListView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('user_detail_<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user_delete_<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('verify_<str:verify_key>/', verify, name='verify'),
    path('send_verify/', send_verify, name='send_verify'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('user_list/', cache_page(30)(UserListView.as_view()), name='user_list'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    is_active = models.BooleanField(default=False, verbose_name='активный')
    verify_token = models.CharField(max_length=20, unique=True, **NULLABLE, verbose_name='ключ верификации')

    first_name = models.CharField(max_length=50, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name='фамилия', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        ordering = ('email',)
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserLoginForm(StyleFormMixin, AuthenticationForm):

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean_username(self):
        cleaned_data = self.cleaned_data['username']

        if User.objects.filter(email=cleaned_data, is_active=False).exists():
            raise forms.ValidationError('Активность аккаунта приостановлена. Проверьте электронную почту.')

        return cleaned_data

users/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from mailing.models import Mailing
from users.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from users.models import User
from users.services import send_verify_email, get_cache_user


class UserLoginView(UserPassesTestMixin, LoginView):
    model = User
    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Вход на портал'
    }

    def test_func(self):
        return not self.request.user.is_authenticated


class UserRegisterView(UserPassesTestMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:send_verify')
    extra_context = {
        'title': 'Регистрация'
    }

    def test_func(self):
        return not self.request.user.is_authenticated

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            new_user.verify_token = get_random_string(length=20)
            new_user.save()
            send_verify_email(new_user)
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('mailing:home')
    extra_context = {
        'title': 'Мой профиль'
    }

    def get_object(self, queryset=None):
        return self.request.user


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    extra_context = {
        'title': 'Удаление аккаунта'
    }
    success_url = reverse_lazy('mailing:home')

    def test_func(self):
        return self.request.user.pk == self.get_object().pk or self.request.user.is_superuser


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    extra_context = {
        'title': 'Список пользователей'
    }

    def test_func(self):
        user = self.request.user
        return (user.is_staff and not user.has_perm('blog.add_article')) or user.is_superuser


class UserDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = User
    extra_context = {
        'title': 'Пользователь'
    }

    def test_func(self):
        user = self.request.user
        return (user.is_staff and not user.has_perm('blog.add_article')) or user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Если убрать строку, вместо текущего пользователя (в меню) будет отображаться выбранный
        context_data['user'] = self.request.user

        context_data['mailings'] = get_cache_user(self.get_object())
        return context_data


@user_passes_test(lambda u: (u.is_staff and not u.has_perm('blog.add_article')) or u.is_superuser)
@login_required
def toggle_activity(request, pk):
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True

    user_item.save()

    return redirect(reverse('users:user_detail', args=[user_item.pk]))


def verify(request, verify_key):
    user_item = get_object_or_404(User, verify_token=verify_key)
    user_item.is_active = True

    # Удаление значения токена для снижения вероятности ошибки уникальности при создании токена для нового пользователя
    user_item.verify_token = None
    user_item.save()
    context = {
        'title': 'Подтверждение регистрации',
        'verifying_message': 'Электронная почта подтверждена.'
    }
    return render(request, 'users/verify_message.html', context)


def send_verify(request):
    context = {
        'title': 'Подтверждение регистрации',
        'verifying_message': 'На вашу электронную почту отправлена ссылка для подтверждения.'
    }
    return render(request, 'users/verify_message.html', context)

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success">Войти</button>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Подтвердить удаление Вашего аккаунта ({{ object.email }})?</p>
                            <button type="submit" class="btn btn-danger">
                                Подтвердить
                            </button>
                            <a href="{% url 'mailing:home' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{title}}
                    </h4>
                </div>
                <div class="card-body">
                    <img class="rounded mx-auto d-block" src="/media/{{ user.avatar }}" alt="#" height="200" width="200">
                    <table class="table">
                        <caption>Информация о пользователе</caption>
                        <tr>
                            <td>Электронная почта</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        <tr>
                            <td>ФИО</td>
                            <td>{{ object|full_name|title }}</td>
                        </tr>
                        <tr>
                            <td>Статус</td>
                            <td>
                                {% if not object.is_staff %}
                                    {% if not object.is_active %}
                                        <a class="btn btn-warning" href="{% url 'users:toggle_activity' object.pk %}">Не активен/подключить к сервису</a>
                                    {% else %}
                                        <a class="btn btn-success" href="{% url 'users:toggle_activity' object.pk %}">Активен/отключить от сервиса</a>
                                    {% endif %}
                                {% else %}
                                    <span>Персонал</span>
                                {% endif %}
                            </td>
                        </tr>

                    </table>
                    {% if user.is_superuser %}
                        <a class="btn btn-danger form-control" href="{% url 'users:user_delete' object.pk %}">Удалить пользователя</a>
                    {% endif %}
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Рассылки
                    </h4>
                </div>
                <div class="card-body">
                    <ul>
                        {% for mailing in mailings %}
                        <li><a href="{% url 'mailing:mailing_detail' mailing.pk %}">{{ mailing }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% if user.is_authenticated %}
                    <img class="rounded mx-auto d-block" src="/media/{{ user.avatar }}" alt="#" height="200" width="200">
                    {% endif %}
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer d-flex">
                    <div>
                        <button type="submit" class="btn btn-success">
                            {% if user.is_authenticated %}
                                Сохранить
                            {% else %}
                                Зарегистрироваться
                            {% endif %}
                        </button>

                        {% if user.is_authenticated %}
                        <a href="{% url 'users:user_delete' object.pk %}" class="btn btn-danger mx-3">
                                Удалить аккаунт
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Аватар</th>
            <th scope="col">Электронная почта</th>
            <th scope="col">ФИО</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td><img class="rounded-5" src="/media/{{ user.avatar }}" alt="#" height="40" width="40"></td>
            <td><a href="{% url 'users:user_detail' object.pk %}">{{ object.email }}</a></td>
            <td>{{ object|full_name|title }}</td>
            <td>
                {% if not object.is_staff %}
                    {% if not object.is_active %}
                        <span>Не активен</span>
                    {% else %}
                        <span>Активен</span>
                    {% endif %}
                {% else %}
                <span>Персонал</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

users/templates/users/verify_message.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                    {{ title }}
                    </h4>
                </div>
                <div class="card-body">
                    {{ verifying_message }}
                </div>
                <div class="card-footer">
                    <a type="button" class="btn btn-outline-success" href="{% url 'users:login' %}">Вход</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}